### ISSUE TITLE
Adding a point every time a page is visited

### ISSUE THREAD

**Issue by jdecampos** [jdecampos/needbundle#7]
In "points management", it must be an action that adds a point **each time** the URL is visited
![image](https://user-images.githubusercontent.com/14194414/27143980-81837840-5130-11e7-9af3-d598fe558d8c.png)

**Comment by kermorgant** [comment]
After a quick check, this is not how the original action works. Every action is logged and kept in history in order to not execute it twice.

This part of the code is shared among the plugin and the core function, so it's not really simple to change that.

You'll have to add several actions, each one with progressive number of page visits to achieve a somehow similar effect.
